---
title: "leadingScorersByZone"
author: "Sahil"
date: "2/19/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Packages
```{r}
library(ggplot2)
library(tidyverse)
library(nbastatR)
library(devtools)
library(extrafont)
library(cowplot)
library(vroom)
```
## Court
```{r}
# Creating court and plotting
circle_points = function(center = c(0,0), radius = 1, npoints = 360){
  angles = seq(0, 2 * pi, length.out = npoints)
  return(data_frame (x = center[1] + radius * cos(angles),
                     y = center[2] + radius * sin(angles)))
}

# Court dimensions and lines
width = 50
height = 94 / 2
key_height = 19
inner_key_width = 12
outer_key_width = 16
backboard_width = 6
backboard_offset = 4
neck_length = 0.5
hoop_radius = 0.75
hoop_center_y = backboard_offset + neck_length + hoop_radius
three_point_radius = 23.75
three_point_side_radius = 22
three_point_side_height = 14

# Court themes
court_themes = list (
  light = list (
    court = 'floralwhite',
    lines = '#999999',
    text = '#222222',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 1,
    hex_border_color = '#000000'
  ),
  dark = list (
    court = '#000004',
    lines = '#999999',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = '#000000'
  ),
  ppt = list(
    court = 'gray20',
    lines = 'black',
    text = '#f0f0f0',
    made = '#00bfc4',
    missed = '#f8766d',
    hex_border_size = 0,
    hex_border_color = 'gray20'
  )
)

# Function to create court based on given dimensions
plot_court = function(court_theme = court_themes$light, use_short_three = FALSE){
  if(use_short_three){
    three_point_radius = 22
    three_point_side_height = 0
  }
  
  court_points = data_frame(
    x = c(width / 2, width / 2, -width / 2, -width / 2, width / 2),
    y = c(height, 0, 0, height, height),
    desc = 'Perimeter'
  )
  
  court_points = bind_rows(court_points, data_frame(
    x = c(outer_key_width / 2, outer_key_width / 2, -outer_key_width / 2, -outer_key_width / 2),
    y = c(0, key_height, key_height, 0),
    desc = 'Outer key'
  ))
  
  court_points = bind_rows(court_points, data_frame(
    x = c(-backboard_width / 2, backboard_width / 2),
    y = c(backboard_offset, backboard_offset),
    desc = 'Backboard'
  ))
  
  court_points = bind_rows(court_points, data_frame(
    x = c(0,0), y = c(backboard_offset, backboard_offset + neck_length), desc = 'Neck'
  ))
  
  foul_circle = circle_points(center = c(0, key_height), radius = inner_key_width / 2)
  
  foul_circle_top = filter(foul_circle, y > key_height) %>%
    mutate(desc = 'foul_circle_top')
    
  foul_circle_bottom = filter(foul_circle, y < key_height) %>%
    mutate(
      angle = atan((y - key_height) / x) * 180 / pi,
      angle_group = floor((angle - 5.625) / 11.25),
      desc = paste0('foul_circle_bottom', angle_group)
    ) %>%
    filter(angle_group %% 2 == 0) %>%
    select(x,y, desc)
  
  hoop = circle_points(center = c(0, hoop_center_y), radius = hoop_radius) %>%
    mutate(desc = "Hoop")
  
  restricted = circle_points(center = c(0, hoop_center_y), radius = 4) %>%
    filter(y >= hoop_center_y) %>%
    mutate(desc = "Restricted")
  
  three_point_circle = circle_points(center = c(0, hoop_center_y), radius = three_point_radius) %>%
    filter(y >= three_point_side_height, y >= hoop_center_y)
  
  three_point_line = data_frame(
    x = c(three_point_side_radius, three_point_side_radius, three_point_circle$x, -three_point_side_radius, -three_point_side_radius),
    y = c(0, three_point_side_height, three_point_circle$y, three_point_side_height, 0),
    desc = 'three_point_line'
  )
  
  court_points = bind_rows(
    court_points,
    foul_circle_top,
    foul_circle_bottom,
    hoop,
    restricted,
    three_point_line
  )
  
  court_points <- court_points
  
  #Final plot creation
  ggplot() +
    geom_path(
      data = court_points,
      aes(x = x, y = y, group = desc),
      color = court_theme$lines
    ) +
    coord_fixed(ylim = c(0, 45), xlim = c(-25, 25)) +
    theme_minimal(base_size = 22) +
    theme(
      text = element_text(color = court_theme$text),
      plot.background = element_rect(fill = 'gray20', color = 'gray20'),
      panel.background = element_rect(fill = court_theme$court, color = court_theme$court),
      panel.grid = element_blank(),
      panel.border = element_blank(),
      axis.text = element_blank(),
      axis.title = element_blank(),
      axis.ticks = element_blank(),
      legend.background = element_rect(fill = court_theme$court, color = court_theme$court),
      legend.margin = margin(-1, 0, 0, 0, unit = 'lines'),
      legend.position = 'bottom',
      legend.key = element_blank(),
      legend.text = element_text(size = rel(1))
    )
}
```
## Data 
```{r}
Sys.setenv("VROOM_CONNECTION_SIZE" = 131072 * 2)

#Fox & Monk
kings <- teams_shots(teams = "Sacramento Kings", seasons = 2023, season_types = "Regular Season")

fox <- kings %>% filter(namePlayer == "De'Aaron Fox", dateGame == "20230224") %>%
  mutate(x = as.numeric(as.character(locationX)) / 10, y = as.numeric(as.character(locationY)) / 10 + hoop_center_y)

monk <- kings %>% filter(namePlayer == "Malik Monk", dateGame == "20230224") %>%
  mutate(x = as.numeric(as.character(locationX)) /10, y = as.numeric(as.character(locationY)) / 10 + hoop_center_y)


#Horizontally flip the data
fox$x <- fox$x * -1
monk$x <- monk$x * -1

fonk <- merge(fox, monk, all = TRUE)

#Kawhi
kawhi <- teams_shots(teams = "Los Angeles Clippers", season = 2023, season_types = "Regular Season") %>% filter(namePlayer == "Kawhi Leonard", dateGame == "20230224") %>%
  mutate(x = as.numeric(as.character(locationX)) / 10, y = as.numeric(as.character(locationY)) / 10 + hoop_center_y)

kawhi$x <- kawhi$x * -1

```
## Plot Data
```{r}
#Kings
kings_shot_chart <- plot_court(court_themes$ppt, use_short_three = F) +
  geom_point(data = fonk, aes(x = x, y = y, color = isShotMade, fill = isShotMade), size = 3, shape = 21, stroke = .5) +
  scale_color_manual(values = c('green4', 'red 3'), aesthetics = 'color', breaks = c('TRUE', 'FALSE'), labels = c('Made', 'Missed')) + 
  scale_fill_manual(values = c('green2', 'gray 20'), aesthetics = 'fill', breaks = c('TRUE', 'FALSE'), labels = c('Made', 'Missed')) +
scale_x_continuous(limits = c(-27.5, 27.5)) +
scale_y_continuous(limits = c(0, 45)) +
  theme(plot.title = element_text(hjust = .5, size = 22, family = 'Comic Sans MS', face = 'bold', vjust = -4), 
  plot.subtitle =  element_text(hjust = .5, size = 10, family = 'Comic Sans MS', face = 'bold', vjust = -8), 
  legend.position = c(.5, .95),
  legend.direction = 'horizontal',
  legend.title = element_blank(),
  legend.text = element_text(hjust = .5, size = 10, family = 'Comic Sans MS', face = 'bold', color = 'black')) +
  
  labs(title = "De'Aaron Fox & Malik Monk vs Clippers",
          subtitle = "87 PTS | 63% FG - 2/24/23" ,
          caption = "@TheSahillKhatri")

 ggdraw(kings_shot_chart) + theme(plot.background = element_rect(fill = 'gray20', color = NA))
 
 #ggsave('kings.png', height = 6, width = 6, dpi = 300)
 
 #Kawhi
 kawhi_shot_chart <- plot_court(court_themes$ppt, use_short_three = F) +
  geom_point(data = kawhi, aes(x = x, y = y, color = isShotMade, fill = isShotMade), size = 3, shape = 21, stroke = .5) +
  scale_color_manual(values = c('green4', 'red 3'), aesthetics = 'color', breaks = c('TRUE', 'FALSE'), labels = c('Made', 'Missed')) + 
  scale_fill_manual(values = c('green2', 'gray 20'), aesthetics = 'fill', breaks = c('TRUE', 'FALSE'), labels = c('Made', 'Missed')) +
scale_x_continuous(limits = c(-27.5, 27.5)) +
scale_y_continuous(limits = c(0, 45)) +
  theme(plot.title = element_text(hjust = .5, size = 22, family = 'Comic Sans MS', face = 'bold', vjust = -4), 
  plot.subtitle =  element_text(hjust = .5, size = 10, family = 'Comic Sans MS', face = 'bold', vjust = -8), 
  legend.position = c(.5, .95),
  legend.direction = 'horizontal',
  legend.title = element_blank(),
  legend.text = element_text(hjust = .5, size = 10, family = 'Comic Sans MS', face = 'bold', color = 'black')) +
  
  labs(title = "Kawhi Leonard vs Kings",
          subtitle = '44 PTS | 72% FG - 2/24/23',
          caption = "@TheSahillKhatri")

 ggdraw(kawhi_shot_chart) + theme(plot.background = element_rect(fill = 'gray20', color = NA))
 
 #ggsave('kawhi_shot_chart.png', height = 6, width = 6, dpi = 300)
```

